spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        password: _000125Ljj
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://106.14.166.169:3306/disk?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
#        url: jdbc:mysql://127.0.0.1:3306/disk?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    resources:
        static-locations : file:C:\\Users\\user\\Videos\\Captures
#    redis:
#        host: 106.14.166.169
#        port: 6379
#        password:
#        jedis:
#            pool:
#                max-active: 8
    redis:
        host: 127.0.0.1
        port: 6379
        password:
        jedis:
            pool:
                max-active: 8
#    security:
#        oauth2:
#            resourceserver:
#                opaquetoken:
#                    introspection-uri:
server:
    port: 9999
logging:
    level:
        root: info
socketio:
    host: localhost
    port: 9099
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
    maxFramePayloadLength: 1048576
  # 设置http交互最大内容长度
    maxHttpContentLength: 1048576
  # socket连接数大小（如只监听一个端口boss线程组为1即可）
    bossCount: 1
    workCount: 100
    allowCustomRequests: true
  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
    upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
    pingTimeout: 6000000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
    pingInterval: 25000

