spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://106.14.166.169:3306/disk?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
        url: jdbc:mysql://127.0.0.1:3306/disk?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    resources:
        static-locations : file:C:\\Users\\user\\Videos\\Captures
#    redis:
#        host: 106.14.166.169
#        port: 6379
#        password:
#        jedis:
#            pool:
#                max-active: 8
    redis:
        host: 127.0.0.1
        port: 6379
        password:
        jedis:
            pool:
                max-active: 8
#    security:
#        oauth2:
#            resourceserver:
#                opaquetoken:
#                    introspection-uri:
server:
    port: 9999
logging:
    level:
        root: info



